"""Add user role

Revision ID: e71ab4e80276
Revises: 3a2ef571ede1
Create Date: 2025-06-11 20:32:16.663265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e71ab4e80276'
down_revision: Union[str, None] = '3a2ef571ede1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('role', sa.String(length=50), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'role')
    # ### end Alembic commands ###
